spring.application.name=DrinkDuel
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=${DRINKDUEL_SECURE_COOKIES:true}
server.servlet.session.timeout=48h
server.forward-headers-strategy=framework
